blank_issues_enabled: false
contact_links:
  - name: Report a data or tooling problem
    url: https://github.com/ProteinQure/monomer-database-source/issues/new
    about: Propose all corrections and changes in the authoritative source repository.
